# Generated by Django 5.0.1 on 2024-02-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_products_options_products_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='company_name',
        ),
    ]
