# Generated by Django 5.0.1 on 2024-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_remove_products_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
