# Generated by Django 5.0.1 on 2024-03-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_rename_product_dec_products_product_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prouct_image',
            new_name='product_image',
        ),
    ]
