# Generated by Django 5.0.1 on 2024-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='line2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
