# Generated by Django 5.0.1 on 2024-03-18 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_useraddress_line2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('order_placed_at', models.DateTimeField(auto_now_add=True)),
                ('product_total_quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_quantity', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('CASH_ON_DELIVERY', 'CASH_ON_DELIVERY'), ('UPI', 'UPI'), ('NET_BANKING', 'NET_BANKING')], default='CASH_ON_DELIVERY', max_length=20)),
                ('total_amount', models.FloatField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.useraddress')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Orders',
            },
        ),
    ]
